liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
#    driver: "gd"
#
   # define your filter sets under this option
   filter_sets:

       # an example thumbnail transformation definition
       # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
       thumbnail:

           # set your image quality defaults
           jpeg_quality:          75
           png_compression_level: 8

           # setup the filter steps to apply for this transformation
           filters:

               # auto rotate the image using EXIF metadata
               auto_rotate: ~

               # strip the image of all metadata
               strip: ~

               # scale and square the image to the given dimensions
               thumbnail:
                   size:          [240, 200]
                   mode:          outbound
                   allow_upscale: true
       preview:

           # set your image quality defaults
           jpeg_quality:          75
           png_compression_level: 8

           # setup the filter steps to apply for this transformation
           filters:

               # auto rotate the image using EXIF metadata
               auto_rotate: ~

               # strip the image of all metadata
               strip: ~

               # scale and square the image to the given dimensions
               thumbnail:
                   size:          [480, 340]
                   mode:          outbound
                   allow_upscale: true
