version: '3'

services:
    data:
        image: busybox
        volumes:
            - ./:/var/www/
            - /vendor
            - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
            - ~/.composer:/root/.composer
            - /tmpfs
    nginx:
        image: nginx
        links:
            - php
        # volumes_from:
        #     - data
        volumes:
            - ./:/var/www/
            - ./vendor/estandarte/docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8008:80"
            - "8448:443"
        environment: 
            - LOCALHOST_UID=1000
            - LOCALHOST_USERNAME=${USER}

    mysql:
        image: mariadb
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: syclass
            MYSQL_USER: syclass
            MYSQL_PASSWORD: syclass
            LOCALHOST_UID: 1000
            LOCALHOST_USERNAME: ${USER}


    php:
        build: ./vendor/estandarte/docker-compose/php
        working_dir: /var/www
        volumes:
            - ./:/var/www/
            - ~/.composer/cache:/composer/cache
        links:
            - mysql:db
        environment: 
            - LOCALHOST_UID=1000
            - LOCALHOST_USERNAME=${USER}
