Syclass\Entity\Admin:
    type: entity
    table: admin
    uniqueConstraints:
        s_username:
            columns:
                - s_username
        s_email:
            columns:
                - s_email
    id:
        pkIId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: pk_i_id
            generator:
                strategy: IDENTITY
    fields:
        sName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: s_name
        sUsername:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            column: s_username
        sPassword:
            type: string
            nullable: false
            length: 60
            options:
                fixed: true
            column: s_password
        sEmail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                default: 'NULL'
            column: s_email
        sSecret:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
                default: 'NULL'
            column: s_secret
        bModerator:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: b_moderator
    lifecycleCallbacks: {  }
