Syclass\Entity\ItemMeta:
    type: entity
    table: item_meta
    indexes:
        fk_i_field_id:
            columns:
                - fk_i_field_id
        s_value:
            columns:
                - s_value
        IDX_90B89217495988B:
            columns:
                - fk_i_item_id
    id:
        sMulti:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: ''''''
            id: true
            column: s_multi
        fkIItem:
            associationKey: true
        fkIField:
            associationKey: true
    fields:
        sValue:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
                default: 'NULL'
            column: s_value
    oneToOne:
        fkIItem:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_item_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
        fkIField:
            targetEntity: MetaFields
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_field_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
