Syclass\Entity\Log:
    type: entity
    table: log
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dtDate:
            type: datetime
            nullable: false
            column: dt_date
        sSection:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: s_section
        sAction:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: s_action
        fkIId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: fk_i_id
        sData:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
            column: s_data
        sIp:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: s_ip
        sWho:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: s_who
        fkIWhoId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: fk_i_who_id
    lifecycleCallbacks: {  }
