Syclass\Entity\Ads:
    type: entity
    table: ads
    repositoryClass: Syclass\Repository\AdsRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        itemId:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
            column: item_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        pubDate:
            type: datetime
            nullable: true
            options:
                default: 'NULL'
            column: pub_date
        site:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        siteId:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                default: 'NULL'
            column: site_id
    lifecycleCallbacks: {  }
