Syclass\Core\Entity\CategoryDescription:
    type: entity
    table: category_description
    indexes:
        fk_i_category_id:
            columns:
                - fk_i_category_id
        fk_c_locale_code:
            columns:
                - fk_c_locale_code
    id:
        category:
            associationKey: true
        locale:
            associationKey: true
        # categoryId:
        #     type: integer
        #     nullable: false
        #     options:
        #         unsigned: true
        #     id: true
        #     column: fk_i_category_id
        # localeCode:
        #     type: string
        #     nullable: false
        #     length: 5
        #     options:
        #         fixed: true
        #     id: true
        #     column: fk_c_locale_code
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                default: 'NULL'
            column: s_name
        description:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                default: 'NULL'
            column: s_description
        slug:
            type: string
            nullable: true
            length: 100
            column: s_slug
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: description
            joinColumns:
                fk_i_category_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: true
        locale:
            targetEntity: Locale
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_c_locale_code:
                    referencedColumnName: pk_c_code
    lifecycleCallbacks: {  }
