Syclass\Core\Entity\Item:
    type: entity
    table: item
    repositoryClass: Syclass\Core\Repository\ItemRepository
    indexes:
        fk_c_currency_code:
            columns:
                - fk_c_currency_code
        fk_i_user_id:
            columns:
                - fk_i_user_id
        fk_i_category_id:
            columns:
                - fk_i_category_id
        idx_price:
            columns:
                - i_price
        idx_s_contact_email:
            columns:
                - s_contact_email
        idx_pub_date:
            columns:
                - dt_pub_date
        idx_b_premium:
            columns:
                - b_premium
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: pk_i_id
            generator:
                strategy: IDENTITY
    fields:
        pubDate:
            type: datetime
            nullable: false
            column: dt_pub_date
        modDate:
            type: datetime
            nullable: true
            options:
                default: 'NULL'
            column: dt_mod_date
        fPrice:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: 'NULL'
            column: f_price
        iPrice:
            type: bigint
            nullable: true
            options:
                unsigned: false
                default: 'NULL'
            column: i_price
        contactName:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
                default: 'NULL'
            column: s_contact_name
        contactEmail:
            type: string
            nullable: false
            length: 140
            options:
                fixed: false
            column: s_contact_email
        ip:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
                default: ''''''
            column: s_ip
        premium:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: b_premium
        enabled:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: b_enabled
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: b_active
        spam:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: b_spam
        secret:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
                default: 'NULL'
            column: s_secret
        showEmail:
            type: boolean
            nullable: true
            options:
                default: 'NULL'
            column: b_show_email
        expiration:
            type: datetime
            nullable: false
            options:
                default: '''9999-12-31 23:59:59'''
            column: dt_expiration
    oneToMany:
        description:
            targetEntity: ItemDescription
            mappedBy: item
            cascade: ['persist']
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_user_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_category_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
        currency:
            targetEntity: Currency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_c_currency_code:
                    referencedColumnName: pk_c_code
            orphanRemoval: false
    lifecycleCallbacks: {  }
