Syclass\Core\Entity\ItemComment:
    type: entity
    table: item_comment
    indexes:
        fk_i_item_id:
            columns:
                - fk_i_item_id
        fk_i_user_id:
            columns:
                - fk_i_user_id
    id:
        pkIId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: pk_i_id
            generator:
                strategy: IDENTITY
    fields:
        dtPubDate:
            type: datetime
            nullable: false
            column: dt_pub_date
        sTitle:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: s_title
        sAuthorName:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: s_author_name
        sAuthorEmail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: s_author_email
        sBody:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: s_body
        bEnabled:
            type: boolean
            nullable: false
            options:
                default: 1
            column: b_enabled
        bActive:
            type: boolean
            nullable: false
            options:
                default: 0
            column: b_active
        bSpam:
            type: boolean
            nullable: false
            options:
                default: 0
            column: b_spam
    manyToOne:
        fkIItem:
            targetEntity: Item
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_item_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
        fkIUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                fk_i_user_id:
                    referencedColumnName: pk_i_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
