Syclass\Entity\LocationsTmp:
    type: entity
    table: locations_tmp
    id:
        idLocation:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            id: true
            column: id_location
        eType:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: e_type
    lifecycleCallbacks: {  }
