Syclass\Core\Entity\Page:
    type: entity
    table: pages
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: pk_i_id
            generator:
                strategy: IDENTITY
    fields:
        internalName:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                default: NULL
            column: s_internal_name
        indelible:
            type: boolean
            nullable: false
            options:
                default: 0
            column: b_indelible
        link:
            type: boolean
            nullable: false
            options:
                default: 1
            column: b_link
        pubDate:
            type: datetime
            nullable: false
            column: dt_pub_date
        modDate:
            type: datetime
            nullable: true
            options:
                default: NULL
            column: dt_mod_date
        order:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: 0
            column: i_order
        meta:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
                default: NULL
            column: s_meta
    oneToMany:
        description:
            targetEntity: PageDescription
            cascade: ['persist']
            mappedBy: page
    lifecycleCallbacks: {  }
